src/main/java/de/jottyfan/auto/AddBean.java
package de.jottyfan.auto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * 
 * @author jotty
 *
 */
public class AddBean {

	private Integer mileage;
	private String fuel;
	private String location;
	private BigDecimal price;
	private BigDecimal amount;
	private String provider;
	private LocalDateTime buydate;
	private String annotation;

	public Integer getMileage() {
		return mileage;
	}

	public void setMileage(Integer mileage) {
		this.mileage = mileage;
	}

	public String getFuel() {
		return fuel;
	}

	public void setFuel(String fuel) {
		this.fuel = fuel;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getProvider() {
		return provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public LocalDateTime getBuydate() {
		return buydate;
	}

	public void setBuydate(LocalDateTime buydate) {
		this.buydate = buydate;
	}

	public String getAnnotation() {
		return annotation;
	}

	public void setAnnotation(String annotation) {
		this.annotation = annotation;
	}
}

src/main/java/de/jottyfan/auto/AddController.java
package de.jottyfan.auto;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class AddController {

	@Inject
	private AddModel addModel;

	@Inject
	private ShowModel showModel;

	public String doStartSession() {
		boolean newSession = addModel.startSession(FacesContext.getCurrentInstance());
		return newSession ? toWelcome() : "/pages/login.jsf";
	}

	public String doInvalidateSession() {
		addModel.invalidateSession(FacesContext.getCurrentInstance());
		addModel.setKey(null);
		return "/pages/login.jsf";
	}

	public String toWelcome() {
		showModel.loadData(FacesContext.getCurrentInstance());
		return "/pages/welcome.jsf";
	}

	public String toAdd() {
		showModel.loadData(FacesContext.getCurrentInstance());
		return "/pages/add.jsf";
	}

	public String doAdd() {
		addModel.add(FacesContext.getCurrentInstance());
		return toWelcome();
	}

	public AddModel getAddModel() {
		return addModel;
	}

	public void setAddModel(AddModel addModel) {
		this.addModel = addModel;
	}

	public ShowModel getShowModel() {
		return showModel;
	}

	public void setShowModel(ShowModel showModel) {
		this.showModel = showModel;
	}
}

src/main/java/de/jottyfan/auto/ApplicationBean.java
package de.jottyfan.auto;

import java.io.IOException;
import java.io.Serializable;
import java.util.Properties;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.core.LoggerContext;
import org.apache.logging.log4j.core.config.Configuration;
import org.apache.logging.log4j.core.config.LoggerConfig;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class ApplicationBean implements Serializable {
	private static final long serialVersionUID = 1L;
	
	/**
	 * get version from maven build
	 * 
	 * @param facesContext
	 * @return
	 */
	public String getVersion(FacesContext facesContext) {
		final Properties prop = new Properties();
		try {
			prop.load(facesContext.getExternalContext().getResourceAsStream("/META-INF/MANIFEST.MF"));
			String version = prop.getProperty("Implementation-Version");
			return new StringBuilder("Version ").append(version == null ? prop.toString() : version).toString();
		} catch (final IOException e) {
			return e.getMessage();
		}
	}

	/**
	 * get all log levels
	 * 
	 * @return the log levels
	 */
	public Level[] getLoglevels() {
		return Level.values();
	}

	/**
	 * get the current log level
	 * 
	 * @return the current log level
	 */
	public String getLoglevel() {
		LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
		Configuration config = ctx.getConfiguration();
		LoggerConfig loggerConfig = config.getLoggerConfig(LogManager.ROOT_LOGGER_NAME);
		Level level = loggerConfig.getLevel();
		return level.name();
	}

	/**
	 * set the loglevel
	 * 
	 * @param loglevel
	 *            the loglevel
	 */
	public void setLoglevel(Level loglevel) {
		LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
		Configuration config = ctx.getConfiguration();
		LoggerConfig loggerConfig = config.getLoggerConfig(LogManager.ROOT_LOGGER_NAME);
		loggerConfig.setLevel(loglevel);
		ctx.updateLoggers();
	}
}

src/main/java/de/jottyfan/auto/EditController.java
package de.jottyfan.auto;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * 
 * @author jotty
 *
 */
@Named
@RequestScoped
public class EditController {

	@Inject
	private EditModel editModel;

	@Inject
	private ShowModel showModel;

	public String toEdit(MileageViewBean bean) {
		if (editModel == null) {
			editModel = new EditModel();
		}
		editModel.setBean(bean);
		return "/pages/edit.jsf";
	}

	public String doUpdate() {
		boolean result = editModel.update(FacesContext.getCurrentInstance());
		if (result) {
			showModel.loadData(FacesContext.getCurrentInstance());
			return "/pages/add.jsf";
		} else {
			return "";
		}
	}

	public EditModel getModel() {
		return editModel;
	}

	public void setModel(EditModel editModel) {
		this.editModel = editModel;
	}

	public ShowModel getShowModel() {
		return showModel;
	}

	public void setShowModel(ShowModel showModel) {
		this.showModel = showModel;
	}
}

src/main/java/de/jottyfan/auto/LinechartController.java
package de.jottyfan.auto;

import java.math.BigDecimal;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.chart.LineChartSeries;

@Named
@RequestScoped
public class LinechartController {
	
	@Inject
	private ShowModel showModel;
	
	private LinechartModel model;
	
	public String toLinechart() {
		LineChartSeries series = new LineChartSeries("Auto 1");
		BigDecimal xMax = new BigDecimal(0);
		BigDecimal xMin = new BigDecimal(10);
		for (MileageViewBean bean : showModel.getData()) {
			series.set(bean.getMileage(), bean.getEuroproliter());
			xMax = xMax.floatValue() < bean.getEuroproliter().floatValue() ? bean.getEuroproliter() : xMax;
			xMin = xMin.floatValue() > bean.getEuroproliter().floatValue() ? bean.getEuroproliter() : xMin;
		}
		model = new LinechartModel(series, xMin, xMax);
		return "/pages/linechart.jsf";
	}

	public LinechartModel getModel() {
		return model;
	}
}

src/main/webapp/pages/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<p:panel id="input" header="Übernahme eines Kassenzettelinhaltes">
				<h:form>
					<h:panelGrid columns="2" columnClasses="label, value" cellpadding="8">
						<h:outputLabel for="mileage" value="Kilometerstand" />
						<p:inputNumber id="mileage" value="#{addModel.addBean.mileage}" maxlength="7" thousandSeparator="" decimalPlaces="0" maxValue="9999999" minValue="0" />
						<h:outputLabel for="fuel" value="Kraftstoff" />
						<p:autoComplete id="fuel" value="#{addModel.addBean.fuel}" completeMethod="#{addModel.filterFuels}" />
						<h:outputLabel for="location" value="Ort" />
						<p:autoComplete id="location" value="#{addModel.addBean.location}" completeMethod="#{addModel.filterLocations}" />
						<h:outputLabel for="price" value="Preis" />
						<p:inputNumber id="price" value="#{addModel.addBean.price}" mask="999,99" symbol="€ " symbolPosition="p" decimalPlaces="2" maxValue="999" minValue="0" decimalSeparator=","
							thousandSeparator="" />
						<h:outputLabel for="amount" value="Menge" />
						<p:inputNumber id="amount" value="#{addModel.addBean.amount}" mask="999,99" symbol=" l" symbolPosition="s" decimalPlaces="2" maxValue="999" minValue="0" decimalSeparator=","
							thousandSeparator="" />
						<h:outputLabel for="provider" value="Tankstellenname" />
						<p:autoComplete id="provider" value="#{addModel.addBean.provider}" completeMethod="#{addModel.filterProviders}" />
						<h:outputLabel for="buydate" value="Rechnungszeitpunkt" />
						<p:datePicker id="buydate" value="#{addModel.addBean.buydate}" locale="de" showButtonBar="true" showIcon="true" showTime="true" pattern="dd.MM.yyyy HH:mm" />
						<h:outputLabel for="annotation" value="Kommentar" />
						<p:inputTextarea id="annotation" value="#{addModel.addBean.annotation}" />
						<p:commandButton action="#{addController.toWelcome}" value="Abbrechen" ajax="false" immediate="true" />
						<p:commandButton action="#{addController.doAdd}" ajax="false" value="Übernehmen" />
					</h:panelGrid>
				</h:form>
			</p:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/edit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<p:panel header="Daten korrigieren">
				<h:form>
					<h:panelGrid columns="2" columnClasses="label, value" cellpadding="8">
						<h:outputText value="ID" />
						<h:outputText value="#{editModel.bean.pk}" />
						<h:outputLabel for="mileage" value="Kilometerstand" />
						<p:inputNumber id="mileage" value="#{editModel.bean.mileage}" maxlength="7" thousandSeparator="" decimalPlaces="0" maxValue="9999999" minValue="0" />
						<h:outputLabel for="fuel" value="Kraftstoff" />
						<p:autoComplete id="fuel" value="#{editModel.bean.fuel}" completeMethod="#{addModel.filterFuels}" />
						<h:outputLabel for="location" value="Ort" />
						<p:autoComplete id="location" value="#{editModel.bean.location}" completeMethod="#{addModel.filterLocations}" />
						<h:outputLabel for="price" value="Preis" />
						<p:inputNumber id="price" value="#{editModel.bean.price}" mask="999,99" symbol="€ " symbolPosition="p" decimalPlaces="2" maxValue="999" minValue="0" decimalSeparator="," thousandSeparator="" />
						<h:outputLabel for="amount" value="Menge" />
						<p:inputNumber id="amount" value="#{editModel.bean.amount}" mask="999,99" symbol=" l" symbolPosition="s" decimalPlaces="2" maxValue="999" minValue="0" decimalSeparator=","
							thousandSeparator="" />
						<h:outputLabel for="provider" value="Tankstellenname" />
						<p:autoComplete id="provider" value="#{editModel.bean.provider}" completeMethod="#{addModel.filterProviders}" />
						<h:outputLabel for="buydate" value="Rechnungszeitpunkt" />
						<p:datePicker id="buydate" value="#{editModel.bean.buydate}" locale="de" showButtonBar="true" showIcon="true" showTime="true" pattern="dd.MM.yyyy HH:mm" />
						<h:outputLabel for="annotation" value="Kommentar" />
						<p:inputTextarea id="annotation" value="#{editModel.bean.annotation}" />
						<p:commandButton action="#{addController.toWelcome}" value="Abbrechen" ajax="false" immediate="true" />
						<p:commandButton action="#{editController.doUpdate}" value="Übernehmen" ajax="false" />
					</h:panelGrid>
				</h:form>
			</p:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/linechart.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<p:panel header="Verlauf der bisherigen Einkäufe">
				<p:chart widgetVar="chart" type="line" model="#{linechartController.model.zoomModel}" style="height: 512px" />
				<h:form>
					<j:buttonGroup>
						<p:commandButton type="button" value="Herauszoomen" icon="fa fa-search-minus" onclick="PF('chart').resetZoom()" />
						<p:commandButton action="#{addController.toWelcome}" value="Abbrechen" ajax="false" immediate="true" />
					</j:buttonGroup>
				</h:form>
			</p:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<h:form styleClass="central240">
				<p:panel header="Login" styleClass="central240">
					<j:floater value="Code">
						<p:password value="#{addModel.key}" style="width: 100%" />
					</j:floater>
					<f:facet name="footer">
						<p:commandButton action="#{addController.doStartSession}" value="anmelden" style="left: 25%; right: 25%" />
					</f:facet>
				</p:panel>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

src/main/webapp/pages/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:head>
	<h:outputStylesheet name="style.css?version=#{applicationBean.getVersion(facesContext)}" library="css" />
</h:head>
<h:body>
	<div class="content">
		<div id="messages">
			<p:messages showDetail="true" skipDetailIfEqualsSummary="true" closable="true" />
		</div>
		<div id="content" style="margin: 8px">
			<ui:insert name="content" />
		</div>
		<div id="logout">
			<h:form rendered="#{addModel.inSession}">
				<j:buttonGroup>
					<p:selectOneMenu value="#{applicationBean.loglevel}">
						<f:selectItems value="#{applicationBean.loglevels}" var="l" itemLabel="#{l.name()}" itemValue="#{l}" />
					</p:selectOneMenu>
					<p:commandButton action="#{addController.doInvalidateSession}" value="Sitzung beenden" icon="fa fa-power-off" ajax="false" immediate="true" />
				</j:buttonGroup>
			</h:form>
		</div>
	</div>
	<div class="footer">
		<div id="footer" style="position: absolute; right: 12px; display: inline">
			<h:outputText value="#{applicationBean.getVersion(facesContext)}" />
		</div>
	</div>
</h:body>
</html>

src/main/webapp/pages/welcome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:j="http://java.sun.com/jsf/composite/jottyfan">
<h:body>
	<ui:composition template="/pages/template.xhtml">
		<ui:define name="content">
			<p:panel header="bisher erfasste Daten">
				<h:form>
					<p:dataTable value="#{showModel.data}" var="e" paginator="true" rows="10" paginatorAlwaysVisible="false">
						<p:column headerText="ID" sortBy="#{e.pk}">
							<p:commandLink action="#{editController.toEdit(e)}" ajax="false" value="#{e.pk}" />
						</p:column>
						<p:column headerText="KM" sortBy="#{e.mileage}" filterable="true">
							<h:outputText value="#{e.mileage}" />
						</p:column>
						<p:column headerText="Preis €" sortBy="#{e.price}" filterable="true">
							<h:outputText value="#{e.price}" />
						</p:column>
						<p:column headerText="Menge l" sortBy="#{e.amount}" filterable="true">
							<h:outputText value="#{e.amount}" />
						</p:column>
						<p:column headerText="Kraftstoff" sortBy="#{e.fuel}" filterable="true">
							<h:outputText value="#{e.fuel}" />
						</p:column>
						<p:column headerText="Ort" sortBy="#{e.location}" filterable="true">
							<h:outputText value="#{e.location}" />
						</p:column>
						<p:column headerText="Tankstelle" sortBy="#{e.provider}" filterable="true">
							<h:outputText value="#{e.provider}" />
						</p:column>
						<p:column headerText="Datum" sortBy="#{e.buydate}" filterable="true">
							<h:outputText value="#{e.buydate}" />
						</p:column>
						<p:column headerText="€ / l" sortBy="#{e.europroliter}" filterable="true">
							<h:outputText value="#{e.europroliter}" />
						</p:column>
						<p:column headerText="Kommentar" sortBy="#{e.annotation}" filterable="true">
							<h:outputText value="#{e.annotation}" />
						</p:column>
					</p:dataTable>
					<j:buttonGroup>
						<p:commandButton action="#{addController.toAdd}" value="Eintrag hinzufügen" ajax="false" icon="fa fa-plus" />
						<p:commandButton action="#{linechartController.toLinechart}" value="Verlauf" ajax="false" icon="fa fa-line-chart" />
					</j:buttonGroup>
				</h:form>
			</p:panel>
		</ui:define>
	</ui:composition>
</h:body>
</html>